name: action

on:
        push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v2
            - name: Write a echo ...
              run: |
                      echo ${GITHUB_REF##*/}
                      echo This is demo file show
                      echo a very basic and easy-to-understand workflow
  job-2:
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v2
            - name: Write another echo ...
              run: |
                      echo ${GITHUB_REF##*/}
                      echo This is demo file show another ...
