name: action

on:
        push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v2
            - name: Write a echo ...
              run: |
                      echo ${GITHUB_REF##*/}
                      echo This is demo file show
                      echo a very basic and easy-to-understand workflow
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v2
            - name: Write another echo ...
              run: |
                      echo ${GITHUB_REF##*/}
                      echo This is demo file show another ...
   deploy:
     name: Deploy
     needs: build
     runs-on: ubuntu-latest
     steps:
             - uses: actions/checkout@v2
             - name: Deploy ...
               run: |
                       echo run....
